# This is a workflow
name: Hello

# Runs on a trigger
on:
  push: 
    branches: [main]

# These are jobs inside workflow
jobs:

 # this is the name of job
  greet:
  #this is a github runner, each job runs on a runner
   runs-on: ubuntu-latest
   steps:
     - name: say hello to users
       run: echo "Hello Dost"
     - name: say hello to username
       run: echo "Hello $USER"
